---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: 11.16.4

platforms:
  - name: ubuntu
    driver:
      vagrantfile_erb: Vagrantfile.erb
      box: ubuntu-14.04-chef
      box_url: http://bit.ly/dsi-ubuntu-1404-box
      network:
        - ['private_network', {ip: '172.28.128.3'}]
      customize:
        memory: 512
        cpus: 1
  - name: debian
    driver:
      vagrantfile_erb: Vagrantfile.erb
      box: debian-7-chef
      box_url: http://bit.ly/dsi-debian-7-box
      network:
        - ['private_network', {ip: '172.28.128.4'}]
      customize:
        memory: 512
        cpus: 1

provisioner:
  name: chef_zero

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[apt::default]
      - recipe[dsi-users::default]
    attributes:
      dsi-users:
        dev: true
        databag:
          name: 'users'
          path: '/tmp/kitchen/encrypted_data_bag_secret'
          encrypted: true
